import axios from 'axios'

export const FETCH_CHARACTERS_START = "FETCH_CHARACTERS_START"
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS"
export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE"
export const CREATE_CHARACTER_START = "CREATE_CHARACTER_START"
export const CREATE_CHARACTER_SUCCESS = "CREATE_CHARACTER_SUCCESS"
export const CREATE_CHARACTER_FAILURE = "CREATE_CHARACTER_FAILURE"
